### PR TITLE
Sure!

### PR DESCRIPTION
**Pull request by Hex4dec**
though i'm not sure about a collab, maybe we can be friends? i'm on [matrix](https://joinmatrix.org): `@pjals:private.coffee`

### CODE REVIEW

**Comment by Hex4dec** [comment]
Hello? @pranavinsight ?

**Comment by pranavinsight** [comment]
@Hex4dec! I told you i am from india.....

**Comment by pranavinsight** [comment]
Btw, i have a Supra dp (i mean profile) picture. 😎😎😎

**Comment by pranavinsight** [comment]
I now have VS Code which is helpful for many reasons... But, before, i slowly sculpted my website with Notepad which was very, very hard....

**Comment by pranavinsight** [comment]
You told that 

> though i'm not sure about a collab, maybe we can be friends? i'm on [matrix](https://joinmatrix.org): `@pjals:private.coffee`

Wait a minute, What IS Matrix? it looks like social media, but we can be friends in GitHub itself. Btw, Create some repos and make yourself famous, so, you can showcase my talent, eg. My talent is to make Html and Css Projects(js not included). Like that, please make some intresting repos to make yourself famous. You can't just >lmao like that...

**Comment by Hex4dec** [comment]
I mean, it would be pretty nice if we didn't depend on a janky comments system to talk to eachother.. Matrix is a chatting protocol, which you can use with clients such as [Element](https://element.io), [Nheko (recommended)](https://nheko-reborn.github.io/), and many more, you can even write one yourself!

**Comment by pranavinsight** [comment]
How to login?

**Pull request merged**
